kougakusai/kougakusai-hp2022

package.json

npm scripts 修正 #12

---

.storybook/main.js
src/components/Button/HomeButton/HomeButton.stories.tsx
src/components/Button/HomeButton/HomeButton.tsx
src/components/Button/HomeButton/index.ts
src/components/Button/MenuButton/MenuButton.stories.tsx
src/components/Button/MenuButton/MenuButton.tsx
src/components/Button/MenuButton/index.ts
src/components/Button/RoundedButton/RoundedButton.stories.tsx
src/components/Button/RoundedButton/RoundedButton.tsx
src/components/Button/RoundedButton/index.ts
src/components/Button/index.ts
src/components/CountDown/CountDown/CountDown.stories.tsx
src/components/CountDown/CountDown/CountDown.tsx
src/components/CountDown/CountDown/index.ts
src/components/CountDown/FlipCalendar/FlipCalendar.stories.tsx
src/components/CountDown/FlipCalendar/FlipCalendar.tsx
src/components/CountDown/FlipCalendar/index.ts
src/components/CountDown/index.ts
src/components/Header/Header.stories.tsx
src/components/Header/Header.tsx
src/components/Header/index.ts
src/components/Typography/Heading/Heading.stories.tsx
src/hooks/useCountDown/index.tsx
src/hooks/useCountDown/useCountDown.ts
src/pages/index.tsx
src/stories/images.stories.tsx
tsconfig.json

Close #15 .
`public/`が`src/`の外にあるために相対パスで書く必要がありましたが、`@public/`で参照可能にしました。

scaffolding #15

---

src/components/Button/RoundedButton/RoundedButton.stories.tsx
src/components/Button/RoundedButton/RoundedButton.tsx

`onClick`は受け取るようにして、実装していません。
クリック時の押下エフェクトはデザインから想像して勝手に付けました。

`詳しく見るボタン`実装 #9

---

src/components/Typography/Paragraph/Paragraph.stories.tsx
src/components/Typography/Paragraph/Paragraph.tsx
src/components/Typography/Paragraph/index.ts
src/components/Typography/index.ts

Paragraphの実装 #20

---

src/components/Copyright/Copyright.stories.tsx
src/components/Copyright/Copyright.tsx
src/components/Copyright/index.ts

Close #22 .
`Copyright`を実装しました。

Copyright実装 #22

---

src/components/Button/HomeButton/HomeButton.tsx
src/components/Button/MenuButton/MenuButton.tsx
src/components/Header/Header.tsx
src/components/Layouts/TopPageLayout/TopPageLayout.tsx
src/components/Link/MenuLink/MenuLink.tsx
src/components/Menu/MenuDrawer/MenuDrawer.tsx
src/pages/_app.tsx

Close #27 .
メニューを反映しました。
メニュー展開時は画面いっぱいに広がり、ホームボタン・メニューボタン・リンクのいずれかをクリックすると収納されます。
アニメーションは指定していません。

メニュー反映 #27

---

src/components/Footer/Footer.tsx
src/components/Landing/Landing.tsx
src/components/Menu/MenuDrawer/MenuDrawer.tsx
src/pages/index.tsx

Close #35 .
トップページを実装しました。
遷移先の無いリンクは一時的にテキスト化しました。
また、協賛企業・団体一覧はコンテンツが無く高さがあまりにも少ないため適当な高さを付与しました。

トップページ実装 #35

---

src/components/Typography/Heading/Heading.tsx

Headingのpxをremに変換

---

src/components/Layouts/DefaultLayout/DefaultLayout.stories.tsx
src/components/Layouts/DefaultLayout/DefaultLayout.tsx
src/components/Layouts/DefaultLayout/index.ts

レイアウト実装 #84

---

src/components/News/NewsDetail/NewsDetail.stories.tsx
src/components/News/NewsDetail/NewsDetail.tsx
src/components/News/NewsDetail/index.ts
src/components/News/index.ts

お知らせ内容表示の実装 #88

---

src/components/ProgramItem/ProgramItem.stories.tsx
src/components/ProgramItem/ProgramItem.tsx
src/components/ProgramItem/index.ts

`ProgramItem`として実装
一応SNSボタンも実装した。
画像のアスペクト比の保持と紹介文のシュリンクには非対応

企画一覧用カード実装 #90

---

src/components/ProgramItem/ProgramItem.stories.tsx

storyの型エラーで`yarn archive`がエラーになったため修正。

storyの型エラー修正

---

src/components/ProgramItem/ProgramItem.stories.tsx
src/data/program/program.tsx
src/pages/contact.tsx
src/pages/index.tsx

`v1.0.0`リリースに伴うコンテンツ修正 #106

---

src/pages/contact.tsx

お問い合わせページ`/contact`へ新たな問い合わせ用メールアドレスを追加

新問い合わせ用メールアドレス追加 #109

---

src/data/program/program.tsx

現時点で分かる情報を追加しました。
（ブランチの数字間違えましたが気にしないでください。）

日立第二高等学校：企画追加 #119

---

src/components/Footer/Footer.tsx

トップページのフッタ修正 #121

---

src/components/Footer/Footer.tsx
src/components/Menu/MenuDrawer/MenuDrawer.tsx

遷移先のないリンクを無効化 #122

---

src/pages/index.tsx

`バス時刻表`：削除 #143

---

src/components/Button/HomeButton/HomeButton.tsx

・コンポーネント内で定義されていたuseMobileViewをsrc/hooks/useMobileViewからimportして使用するように変更。

useMobileViewの実装を統一

---

README.md

まだ情報としては最低限しか書いてませんが、間違いがなければ一旦これでマージしてください。

readme使用技術、デザイン追記

---

src/components/Footer/Footer.tsx
src/pages/site-policy.tsx

文章は`Figma`からのコピーです。
このページへのリンクは、`index`ページの`footer`からのみです。
@ujimattya 
他ページの文章欄は背景色がページ背景色(`#f0eeee`)ではなく、白色(`#ffffff`)ですが、このページはページ背景色のままでよいですか？

`site-policy`：実装 #139

---

src/components/BusTimeTable/BusTimeTable.tsx
src/components/Menu/MenuDrawer/MenuDrawer.tsx
src/data/bus/bus.tsx
src/pages/access.tsx

ページ内容に合わせて`BusTimeTable`も少し修正
徒歩時間は、`Yahoo地図`・`Google Maps`を参考

`accessページ`：実装 #141

---

src/components/News/NewsDetail/NewsDetail.tsx
src/pages/news/index.tsx

`お知らせ一覧ページ`：デザイン修正 #169

---

src/components/Button/LinkButton/LinkButton.stories.tsx
src/components/Button/LinkButton/LinkButton.tsx
src/components/News/NewsDetailCard/NewsDetail.stories.tsx
src/components/News/NewsDetailCard/NewsDetailCard.tsx
src/components/News/NewsDetailCard/index.ts
src/pages/news/[id].tsx
src/pages/news/index.tsx

`/pages/news/[id].tsx`
- `Dynamic Routing`が正しく実装できているかの確認お願いします。
- `build`して動作確認しましたが、もう一度確認お願いします。

お知らせ詳細ページ追加 #170

---

src/components/News/NewsDetail/NewsDetail.stories.tsx
src/components/News/NewsDetail/NewsDetail.tsx
src/components/News/NewsDetailCard/NewsDetailCard.tsx
src/components/News/NewsItem/NewsItem.tsx

Close #97 .
型エラーでビルドできなかったため解消

newsDataの型定義共通化 #97

---

src/pages/index.tsx

最大幅は`600px`で`footerバナー`等の幅へ合わせました。

`index>お知らせ`最大幅：追加

---

src/components/Footer/Footer.tsx
src/pages/precaution.tsx

ページパス：`/precaution`
リンクは、`フッター`からのみ

`ご来場に関する注意事項`ページ：追加 #201

---

src/data/news/news.tsx

更新日：`2022/11/01`
注意事項ページへのパス：`/precaution`
#206 マージ後にマージしてください。

お知らせ：`ご来場に関する注意事項が更新されました。`：追加

---

src/components/Menu/MenuDrawer/MenuDrawer.tsx

雨天決行：追記 #203

---

src/components/News/NewsItem/NewsItem.tsx
src/components/News/NewsList/NewsList.tsx

`Topお知らせ`：リンク化 #211

---

src/components/KitchenCar/KitchenCarImg/KitchenCarImg.tsx
src/components/KitchenCar/KitchenCarImg/index.ts
src/components/KitchenCar/index.ts
src/pages/kitchen-car.tsx

`/component/KitchenCar/KitchenCarImg/KitchenCarImg.tsx`へ切り出しました。
`kitchenCarData`の型については #195 で置き換えていただければ。

`KitchenCarImg`コンポーネント：切り出し #193

---

src/data/sponsor/sponsor.ts

協賛企業追加 #217

---

src/pages/program.tsx

`スタンプラリー企画表示`：削除 #222

---

src/components/EndCard/EndCard.stories.tsx
src/components/EndCard/EndCard.tsx
src/components/EndCard/index.ts
src/components/Landing/Landing.tsx

`EndCard`コンポーネント：追加
`Landing.tsx`の`l.39`と`l.41`を入れ替えることで、カウントダウンと開催後の表示が変わります。

終了後表示用コンポーネント:実装
