- package.json
`kougakusai_hp_2022.tar.gz`がカレントディレクトリに出力される。
回答すると`out/`が出てくる。
> npm scripts に圧縮コマンド追加 #51

- src/components/Button/LinkButton/LinkButton.stories.tsx
- src/components/Button/LinkButton/LinkButton.tsx
- src/components/Button/LinkButton/index.ts
- src/components/Button/index.ts
レスポンシブ対応はデザインがないのでまだですが、形にはなったと思います。
- 遷移先は追加した`href`プロパティから指定します。
`LinkProps`がうまく扱えなかったから。
実装が想定しているものと合っているか確認お願いします。
> `LinkButton`実装

- src/components/Link/SmallLink/SmallLink.stories.tsx
- src/components/Link/SmallLink/SmallLink.tsx
- src/components/Link/SmallLink/index.ts
- src/components/Link/index.ts
Close #24 .
デザインデータではテキストと下線の間に僅かに隙間があるように見えたので、（デザインデータのCSSプロパティには存在しませんが）`text-underline-offset`を設定しました。
> SmallLink実装 #24

- src/components/Sponsor/SponsorList/SponsorList.stories.tsx
- src/components/Sponsor/SponsorList/SponsorList.tsx
- src/components/Sponsor/SponsorList/index.ts
- src/components/Sponsor/index.ts
Close #32 .
`SponsorList`を実装しました。
このコンポーネントで決めているのは見出しだけで、内容は使用者が`children`で指定可能になっています。
一覧のコンテンツ次第ですが、`SponsorList`は協賛企業・団体様のデータを与えるコンポーネントになるかもしれません。その際は内容を`children`で指定するのではなくこのコンポーネントに直接書き込む実装に変更することになると思います。
いずれにせよ、現時点では内容が空なので特に何も配置していません。
> 協賛一覧実装 #32

- src/contexts/MenuContext/MenuContext.tsx
- src/contexts/MenuContext/index.ts
- src/hooks/useCloseMenu/index.ts
- src/hooks/useCloseMenu/useCloseMenu.ts
- src/hooks/useMenuOpen/index.ts
- src/hooks/useMenuOpen/useMenuOpen.ts
- src/hooks/useToggleMenu/index.ts
- src/hooks/useToggleMenu/useToggleMenu.ts
- src/pages/_app.tsx
メニューの開閉状態の`state`とそれを toggle する関数を`Context`でアクセスできるようにしました。
UI の変更はないのでロジックだけ確認していただければと思います。
メニューの開閉状態の`state`を使用する場合は`useMenuOpen`、メニューの開閉状態を toggle する関数を使用する場合は`useToggleMenu`を使用すれば良いように作成しました。
```ts
// state を使う場合
const menuOpen = useMenuOpen();
// toggle 関数を使う場合
const toggleMenu = useToggleMenu();
```
> MenuContext実装 #26

- src/components/Menu/MenuDrawer/MenuDrawer.stories.tsx
- src/components/Menu/MenuDrawer/MenuDrawer.tsx
- src/components/Menu/MenuDrawer/index.ts
- src/components/Menu/index.ts
Close #25 .
メニューを実装しました。
PC版ではリンクの並び順がデザインと異なっていますが、`grid-auto-flow`を`column`にすればデザインデータに合わせることも可能です。
> メニュー実装 #25

- src/components/Notification/NotificationItem/NotificationItem.stories.tsx
- src/components/Notification/NotificationItem/NotificationItem.tsx
- src/components/Notification/NotificationItem/index.ts
- src/components/Notification/index.ts
- src/components/Typography/Paragraph/Paragraph.tsx
Close #29 .
お知らせを実装しました。
`Paragraph`の`font-weight`が間違っていたので修正しています（メニューで使用していますが影響はありません）。
> お知らせ実装 #29

- src/components/About/About.stories.tsx
- src/components/About/About.tsx
- src/components/About/index.ts
- src/components/Marquee/Marquee.tsx
Close #31 .
「こうがく祭とは」を実装しました。
`Marquee`のバグ修正も含みます。
`<style>`は後から読み込まれたものが優先されるため、
最後に配置した`Marquee`の`direction`によって`.marquee-text`の`animation`の値が決まってしまい、`direction`の異なる`Marquee`が共存できていないようでした。
`direction`ごとにクラスを用意しクラス名を振り分けて対応しました。
> 「こうがく祭とは」実装 #31

- src/components/Button/CopyButton/CopyButton.stories.tsx
- src/components/Button/CopyButton/CopyButton.tsx
- src/components/Button/CopyButton/index.ts
- src/components/Popover/Popover.stories.tsx
- src/components/Popover/Popover.tsx
- src/components/Popover/index.ts
- src/hooks/useClipboard/index.ts
- src/hooks/useClipboard/useClipboardLink.ts
- src/hooks/useClipboard/useClipboardText.ts
- tailwind.config.js
`footer`のコピーボタンも機能実装がまだでしたので、`CopyButton`として、またその中で`useClipboardLink`を実装しました。
- `CopyButton`
こうがく祭公式サイトへのリンクをコピーするボタン
コピーボタンに汎用性が必要ない（公式リンクコピーしか実装しない）なら、リンクなどを固定化しようと思います。
- `useClipboardLink`
リンクをコピーする関数を返す`hook`
リンクのプレーンテキストと、ハイパーリンクをコピーする
他所でコピーする箇所がないなら、`hook`化せずに、`CopyButton`内に直書きしようかと
- `useClipboardText`
テキストをコピーする
同上
リンクコピーの機能（特にハイパーリンク）は`.docs`などで試すとわかると思います。
コピー時のエフェクトは、要らないまたはデザイン変更などありましたら、お伝えください。
> `CopyButton`：クリップボードボタン実装 #79

- src/components/Button/MenuButton/MenuButton.tsx
- src/components/Landing/Landing.tsx
`images.stories.tsx`のパスは`import`方式だと、`Storybook`で画像の詳細（`src`・`width`・`height`）がみられるので、変更していませんが、これも変更しますか？
> 画像パス：`import`→`src`へ統一 #50

- src/components/Footer/Footer.tsx
- src/components/Layouts/DefaultLayout/DefaultLayout.tsx
- src/components/Menu/MenuDrawer/MenuDrawer.tsx
- src/pages/contact.tsx
Close #86 .
お問い合わせページを実装しました。
ただし、`DefaultLayout`にて、コンテンツが少ない場合でもフッタがページ最下部になるように修正しました。
また、トップページやメニューからお問い合わせページへ遷移できるように修正しました。
> お問い合わせページ実装 #86

- src/components/BusTimeTable/BusTimeTable.tsx
`white-space: 'nowrap';`を削除
改行位置が汚くなりますが、その修正は要検討（原因不明なため）
> 時刻表の見出し行が崩れる修正 #132

- src/components/Footer/Footer.tsx
- src/components/Menu/MenuDrawer/MenuDrawer.tsx
`Menu`・`Footer`のリンクの内未実装のものを非表示化
> 無効リンク非表示化 #138

- src/components/Footer/Footer.tsx
`FireFox`（端末エミュレート無でも）で表示させると、似たようなレイアウト崩れが発生したので、`FireFox`で修正できていればおそらく直っていると思います。
必ず、`iPhone`所持者の方に確認して頂きたいです。
> `SNSアイコン`レイアウト：修正

- src/components/Footer/Footer.tsx
- src/pages/privacy-policy.tsx
`サイトポリシーページ`のデザインを参考
リンクは`indexページ`の`footer`からのみ。
> `privacy-policyページ`：実装 #140

- src/components/Footer/Footer.tsx
- src/components/TwitterTimeline/TwitterTimeline.stories.tsx
- src/components/TwitterTimeline/TwitterTimeline.tsx
- src/components/TwitterTimeline/index.ts
[公式埋め込みツール](https://publish.twitter.com/?dnt=1&lang=ja&query=https%3A%2F%2Ftwitter.com%2Fkougakufes&widget=Timeline)を使用。
`Desktop版`は`公式Web版Client`の幅と同じにしました。
> `TwitterTimeline`：追加 #118

- .dockerignore
- Dockerfile
- README.md
- next.config.js
トップページ以外のページでブラウザをリロードすると404または403になる。
1. `next.config.js`の`trailingSlash`を`false`にする
2. README の手順に従い docker コンテナを起動
3. ブラウザで localhost:3000 にアクセスし、トップページ以外の任意のページでリロード
（404や403にはならないが適切な html が返却されていないことが分かる）
例えば`/program`でリロードすると`/program/index.html`を取得しようとする。
しかし、`trailingSlash`が`false`だと Next.js は`/program.html`を生成するため`/program/index.html`が見つからない。
`trailingSlash`を`true`に設定し、`/program`を`/program/index.html`として生成するように修正。
Close #112 .
> 更新時にエラーが出る #112

- next.config.js
- package.json
- yarn.lock
Dependabot の警告は Storybook の依存先だが、Storybook を更新しても当該パッケージのバージョンは更新されていなかったため Next.js のみ更新した。
> Next.js 12.3 へアップグレード #44

- src/components/ProgramItem/ProgramItem.tsx
- src/data/program/program.tsx
- src/pages/program.tsx
`PDFファイル`は`a`タグで、開くようにしています。（`iFrame`も可）
`PDFファイル`が合っているか確認お願いします。（最終版ではない場合は、`Issue`を立てておいてください）
事前申し込み必須企画データの追加はしていません。（表示には対応しました。）
> `企画一覧ページ`：デザイン変更 #172

- src/hooks/useCountDown/useCountDown.ts
カウントダウンの値を2022年11月6日0時から逆算して計算するように修正。
> カウントダウンの値を修正
